package com.example.taskbeats.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

@Entity
data class Task (
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val description: String
) : Serializable

// O que fizemos com o PrimaryKey foi informar que o ID é nossa chave principal e que não pode ter ids repetidos.
// E o autoGenerated é justamente pra criar o id automaticamente. Iniciamos com o primeiro ID sendo 0;